### ISSUE TITLE
mkdir has a default of exist_ok=False, but spec expects True?

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/adlfs#134] opened 2020-11-19 09:30 UTC
The `mkdir` implementation here has a default of `exist_ok=False`:

https://github.com/dask/adlfs/blob/54d5826627a25dc8541e35754bf4e9512543a027/adlfs/spec.py#L896-L901

However, when looking at eg the local FileSystem implementation of the core `fsspec` library, there it clearly is OK with creating a directory that already exists:

https://github.com/intake/filesystem_spec/blob/e6596825b5df0d43a7590ff82f50f2b1fead3ab3/fsspec/implementations/local.py#L31-L36

This seems to be a difference between `mkdir` and `mkdirs` (where this last one indeed has a default of `exist_ok=False`). Should this default be changed for `mkdir`?

**Comment by hayesgb** [comment] 2020-11-19 20:26
Thanks @jorisvandenbossche.  Question for @martindurant 

Per [fsspec, exist_ok=True should raise an exception if the target exists](https://github.com/intake/filesystem_spec/blob/c1c1176bf53eedc7d3d0e0ff1ecf07eb2e53d86a/fsspec/spec.py#L249).  This means that the LocalFileSystem [makedirs](https://github.com/intake/filesystem_spec/blob/f236c4f3aeba244d40f8e25102ceb9aba25fe48b/fsspec/implementations/local.py#L31), where create_parents=True would be expected to raise an exception.  However, [os.makedirs()](https://github.com/intake/filesystem_spec/blob/f236c4f3aeba244d40f8e25102ceb9aba25fe48b/fsspec/implementations/local.py#L31) uses the opposite convention for the boolean exist_ok.  Should the docs be updated for fsspec?

Looks like [s3fs](https://github.com/dask/s3fs/blob/1f8e71619c72ebc427b6e881c3622bbbbb9aa576/s3fs/core.py#L612) uses the convention followed by os.

**Comment by martindurant** [comment] 2020-11-19 20:40
Yeah, it looks like the docstring has it the wrong way around

**Comment by hayesgb** [comment] 2020-11-21 14:47
@jorisvandenbossche and @martindurant.

Based on the cross-reference with [this issue](https://github.com/intake/filesystem_spec/issues/479), what do we want to align on for the expected behavior of makedirs and mkdir?  @jorisvandenbossche -- if we align to the Python [convention for os](https://docs.python.org/3/library/os.html#os.makedirs), then I would reimplement mkdir as makedirs, with the behavior described there, and propose a change to the fsspec docstring.  

From [the Python docs](https://docs.python.org/3/library/os.html#os.mkdir), mkdir does not include the "create_parents" keywords, so I would propose dropping that from fsspec, and aligning to the Python os convention.

Thoughts?

**Comment by jorisvandenbossche** [comment] 2020-11-23 09:44
Apart from `os.mkdir/makedirs`, there is also `patlib.Path.mkdir` as a reference (https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir), which has a `parents` keyword. 

> mkdir does not include the "create_parents" keywords, so I would propose dropping that from fsspec, and aligning to the Python os convention.

Personally, I would not remove the keyword since it is quite useful (and not all implementations have a `makedirs` method), but another option could also be to change the default, so that the default behaviour will match `os.mkdir` / the default of `Path.mkdir`, but still allow to get the behaviour of `makedirs` if desired.

**Comment by hayesgb** [comment] 2021-01-15 16:24
This is addressed in #165 .  Note that create_parents will create a container if it is missing.

**Closed by hayesgb** 2021-01-15 16:24 UTC
