### ISSUE TITLE
abfs gen2 implementation based on azure.storage.filedatalake?

### ISSUE THREAD

**Issue by hoffmann** [dask/adlfs#31] opened 2019-12-23 01:05 UTC
Microsoft has released the beta of https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake.

While the current abfs implementation using multi-protocol access works fine, the azure-storage-file-datalake client exposes some nice features for hierarchical namespace like atomic delete and moves semantics for directories.

To get used to the api I have written a demo implementation https://github.com/hoffmann/fsspec_adls

@hayesgb, @martindurant what are your plans for the abfs gen2 implementation?

**Comment by hayesgb** [comment] 2019-12-25 18:19
Thanks for sharing this @hoffmann.  

To answer your question, as you're no doubt aware, Microsoft has been making significant changes to the Azure Datalake API with the move from ~v2 to v12.  The intention is to first get an offering stable using the v2 API with a solid test and release pipeline, with an eye toward migrating to the v12 blob-storage API.  When the first piece is done, it might make sense to consider the filedatalake API if its stable at that point.

**Comment by hayesgb** [comment] 2020-02-15 22:13
Closing this as a duplicate of #15

**Closed by hayesgb** 2020-02-15 22:13 UTC
