### ISSUE TITLE
`ls` on empty container throws FileNotFoundError

### ISSUE THREAD

**Issue by jamesmyatt** [dask/adlfs#64] opened 2020-06-08 23:28 UTC
Working on reproducing #63, I've realised there's a more fundamental problem with `ls`, which is that it doesn't work with empty containers. It throws a FileNotFoundError rather than returning `[]`.

See: https://github.com/dask/adlfs/pull/62/commits/1b1cd42038c5a02b54cee58a927d8dc8a7b88ede

Failure: https://dev.azure.com/dask-dev/dask/_build/results?buildId=1242&view=logs&j=d090b295-8b65-5b33-df45-4b0e4ec519f8&t=8e34badb-79ac-5acb-45f0-df0af76ba649&l=133

**Comment by andersbogsnes** [comment] 2020-06-09 06:52
Could be related to my issue #59 - the root cause of that is also an `ls` issue

**Comment by jamesmyatt** [comment] 2020-06-09 12:32
@andersbogsnes , I agree they seem related

**Comment by hayesgb** [comment] 2020-08-02 14:39
Fixed in 0.3.1.

**Closed by hayesgb** 2020-08-02 14:39 UTC
